import { useState, useEffect } from 'react'
import { suggestCharts } from '../services/ai'
import ChartCard from './ChartCard'
import ColumnSelector from './ColumnSelector'

export default function InsightDashboard({ dataset, charts, onChartsGenerated }) {
  const [loading, setLoading] = useState(false)
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false)

  // Auto-generate charts with smart defaults on first load
  useEffect(() => {
    if (dataset && !hasAutoGenerated && (!charts || charts.length === 0)) {
      handleGenerate()
      setHasAutoGenerated(true)
    }
  }, [dataset])

  const handleGenerate = async (selectedColumns = null) => {
    setLoading(true)
    try {
      const suggested = await suggestCharts(dataset.columns, dataset.rows, selectedColumns)
      onChartsGenerated(suggested)
    } catch (err) {
      console.error('Chart generation failed:', err)
    } finally {
      setLoading(false)
    }
  }

  const handleColumnApply = (selectedCols) => {
    handleGenerate(selectedCols)
  }

  // Show loading skeleton on first auto-generate
  if (loading && (!charts || charts.length === 0)) {
    return (
      <div>
        <div style={{ textAlign: 'center', marginBottom: 'var(--space-5)' }}>
          <div style={{
            display: 'inline-flex', alignItems: 'center', gap: 'var(--space-3)',
            padding: 'var(--space-3) var(--space-5)', borderRadius: 'var(--radius-md)',
            background: 'var(--color-primary-dim)', color: 'var(--color-primary)',
            fontSize: 'var(--font-size-base)', fontWeight: 500
          }}>
            <span className="spinner" /> Analyzing your data and generating insights...
          </div>
        </div>
        <div className="chart-grid">
          {[1, 2, 3, 4].map((i) => (
            <div key={i} className="chart-card animate-in" style={{ animationDelay: `${i * 0.1}s` }}>
              <div className="skeleton skeleton-text" style={{ width: '60%', height: 18 }} />
              <div className="skeleton skeleton-chart" style={{ marginTop: 'var(--space-4)' }} />
              <div className="skeleton skeleton-text" style={{ marginTop: 'var(--space-4)', width: '80%' }} />
            </div>
          ))}
        </div>
      </div>
    )
  }

  return (
    <div>
      {/* Column Selector — always visible once charts exist */}
      <div style={{ marginBottom: 'var(--space-5)' }}>
        <ColumnSelector
          dataset={dataset}
          onApply={handleColumnApply}
          loading={loading}
        />
      </div>

      {/* Chart Grid */}
      {charts && charts.length > 0 && (
        <div className="chart-grid">
          {charts.map((chart, i) => (
            <ChartCard key={chart.id} chart={chart} delay={i} />
          ))}
        </div>
      )}
    </div>
  )
}
